### ISSUE TITLE
[environment] metric to reason about how pivotal a given apple is

### ISSUE THREAD

**Issue by quinn-dougherty** [RedTachyon/cpr_reputation#33]
make value of an apple inversely proportional to how many neighbor apples it has

**Comment by RedTachyon** [comment]
Alternative metric: three discrete values (types) of apples:

Type 0: there is another apple in range (i.e. it can immediately regrow)

Type 1: there isn't another apple in range, but another spot in range is either type 0 or type 1 (i.e. it can regrow at some point in the future)

Type 2: there isn't another apple in range, and all other spots in range are type 2 (i.e. it can never regrow)

**Comment by quinn-dougherty** [comment]
@RedTachyon 
> Type 1: there isn't another apple in range, but another spot in range is either type 0 or type 1 (i.e. it can regrow at some point in the future)

I'm adjusting this spec to say "if anything in a radius of 3 is 0 then it's a 1" (in fact radius of neighbor_kernel.shape[0] // 2 + 1)
