### ISSUE TITLE
[meta] graphing behavioral metrics

### ISSUE THREAD

**Issue by bengreenberg5** [RedTachyon/cpr_reputation#39]
Start collecting metrics on reward/reputation/shooting/episode length over time. Save a graph at the end of training.

**Comment by quinn-dougherty** [comment]
We probably want this https://en.wikipedia.org/wiki/Gini_coefficient#Calculation

**Comment by quinn-dougherty** [comment]
![Screenshot from 2021-05-08 21-08-57](https://user-images.githubusercontent.com/39039420/117552148-a3a82280-b041-11eb-93e0-b88744d53e77.png)
